version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: home_db
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-your_secure_password}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # MQTT Broker (Mosquitto)
  mqtt:
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped

  # Flask Backend
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend:/app/Backend
      - ./Backend/certs:/app/Backend/certs
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-your_secure_password}
      - POSTGRES_DB=home_db
      - MQTT_BROKER_URL=mqtt
      - MQTT_BROKER_PORT=1883
    depends_on:
      db:
        condition: service_healthy
      mqtt:
        condition: service_started

  # React Frontend
  frontend:
    build:
      context: ./Frontend/react_frontend
      dockerfile: Dockerfile
    volumes:
      - ./Frontend/react_frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
      - REACT_APP_MQTT_URL=ws://mqtt:9001
      - REACT_APP_ENCRYPTION_KEY=your-encryption-key
    depends_on:
      - backend

volumes:
  postgres_data: